### ISSUE TITLE
Purge tower for timelapses

### ISSUE THREAD

**Issue by manduulenkhbat** [mainsail-crew/moonraker-timelapse#107]
I'm having a problem with filament oozing out little too much to my taste no matter how much I retract(partly because I'm using DSLR with gphoto2 and downloading/deleting the shot from SD card right away and it requires 7sec which is bit too long) so I was just wondering around and it just hit me that purge tower from multicolor printing might be a good solution. so the idea is - to park toolhead in the back, then trigger timelapse shot/frame, purge a box/tower, then continue to the part printing. Would it be something we could implement with toggle option? thanks!

**Comment by zellneralex** [comment]
Honestly speaking, not as a toggle option. There are simple to many variables you need to take into conclusions if you try to let’s say print a 10x10 mm square layer. It’s starts with simple questions to define where and ends with more komplex once like how much filament to extrude. All that would need to be done outside of the slicer and in real time.

Purge towers are normally added by the slicer and that’s the way I would recommend you to do that also. Place an object in a corner and insure it is the first that is printed after a layer change. How you can reach that goal will depend on the slicer.
