### ISSUE TITLE
Documentation - Change the Resolution of your Camera - Mainsail link does not exist

### ISSUE THREAD

**Issue by Taubin** [mainsail-crew/moonraker-timelapse#110]
Most likely just a small issue, but the link for mainsail's documentation on multicam linked [here](https://github.com/mainsail-crew/moonraker-timelapse/blob/main/docs/configuration.md#change-the-resolution-of-your-camera) does not exist. It goes to a 404 page, and searching their documentation for "multicam" does not give any results.

**Comment by FrYakaTKoP** [comment]
yes, mainsail docs changed alot couple weeks ago i will fix this next weekend

**Comment by FrYakaTKoP** [comment]
fixed with 57bec0dec80e5058eda13cd3586bc2bda0632900

Thanks for the report, closing this issue now
