### ISSUE TITLE
is there a way to change the default rendering frame from 2 to 10? thanks

### ISSUE THREAD

**Issue by drumstick77** [mainsail-crew/moonraker-timelapse#123]

**Comment by FrYakaTKoP** [comment]
sorry can you clearfy what do you mean with "default rendering frame"? Only thing i can think of whould be rendering Threads, which is hardcoded to 2 atm.

**Comment by drumstick77** [comment]
when you click on the timelapse option on the left within moonraker page, if you've just done one print with timelapse, to right of that screen, you can normally see an option if we want to re-render it using different frame (hence longer timelapse video).
Currently the default number of frame is two, so that's what got generated automatically. What I'm trying to know is if there's a way to change that from 2 to 10 frames by default. Hope that's clear. cheers

**Comment by FrYakaTKoP** [comment]
ok that's easy, just go to the settings menu of your webinterface and change the "Output Framerate" to your desired value. 

In Mainsail:
![image](https://github.com/mainsail-crew/moonraker-timelapse/assets/10913183/f5d10f57-af88-4076-a122-b06c8a606f67)
![image](https://github.com/mainsail-crew/moonraker-timelapse/assets/10913183/8a4384a5-e90e-48ae-8933-4f66ab85a0b8)
![image](https://github.com/mainsail-crew/moonraker-timelapse/assets/10913183/b5ba9f93-24e7-47e6-8421-a8a95c73d953)

in Fluidd:
![image](https://github.com/mainsail-crew/moonraker-timelapse/assets/10913183/879ecd51-6e95-45d4-9973-034d97f6b03a)
![image](https://github.com/mainsail-crew/moonraker-timelapse/assets/10913183/2ce7674a-714c-408c-99ea-91795eb88568)
![image](https://github.com/mainsail-crew/moonraker-timelapse/assets/10913183/51e48961-c328-49d0-8954-4670c30bea71)

Strange is that your default is 2 fps, normally it should be 30.  If changing it in the webui doesn't work i would need a moonraker.log to see what's wrong. Most likely you have defined `output_framerate:` in your moonraker.conf

i'm closing this issue, feel free to reopen it if your problem persists or have additional questions to that topic

**Comment by drumstick77** [comment]
AWESOME! So easy and yet I've missed it! Cheers!
