### ISSUE TITLE
[Makefile:20: install] Error 100

### ISSUE THREAD

**Issue by sdw03262** [mainsail-crew/moonraker-timelapse#127]
I have included a screen shot of the error. it preventing me from installing timelapse on my printer.

![Screenshot 2023-07-29 145408](https://github.com/mainsail-crew/moonraker-timelapse/assets/140916849/c79ec1b7-22c4-46c7-b4f2-ea7d9ae30a12)

**Comment by sdw03262** [comment]
I am fairly new to python. any chance you could point me in the direction of a work around or solution for that issue?

**Comment by sdw03262** [comment]
Thank you for the help

**Comment by sdw03262** [comment]
@mryel00 thanks for the help. I had to update the time and date with timedatectl set-ntp yes but it appears to have cleared up the issue.

**Comment by mryel00** [comment]
That's good. I'm glad that I could help you.

The crowsnest part was just added in case you want to use crowsnest for your camera stream.
