### ISSUE TITLE
updating timelapse reports a error but does the update

### ISSUE THREAD

**Issue by FrYakaTKoP** [mainsail-crew/moonraker-timelapse#14]
when updating timelapse the dummy service try to restart moonraker which returns a error, even though it's working properly.

![image](https://user-images.githubusercontent.com/10913183/142738242-a83de1e9-6e64-4dc7-ae43-05c38f70e7f4.png)

The problem is issuing a restart of the dummy service within a child process of moonraker (shell command to restart the service) fails because the process it self will be reset. There is no solution to this at the moment. Moonraker does just ignore the error when restarting moonraker service within the frontend, i can't do this without modifing moonraker code to include timelapse dummy service.

**Comment by zellneralex** [comment]
This is fixed with the updated updater section by adding the manged_services
