### ISSUE TITLE
request to enable or disable message in console " Timelapse: disabled, take frame ignored "

### ISSUE THREAD

**Issue by jpbnto** [mainsail-crew/moonraker-timelapse#143]
![image](https://github.com/mainsail-crew/moonraker-timelapse/assets/91659388/e1f5f08a-a5ad-4698-abc8-54bedb782dd1)

**Comment by zellneralex** [comment]
Use 
<img width="903" alt="image" src="https://github.com/mainsail-crew/moonraker-timelapse/assets/37265689/9980b1f5-df3c-48ff-8719-0d2c8a2b0f16">
