### ISSUE TITLE
conflicted with klipper_tmc_autotune

### ISSUE THREAD

**Issue by Rojer-x86** [mainsail-crew/moonraker-timelapse#147]
this plugin conflicted with plugin klipper_tmc_autotune

after installation the plugin worked
but after reboot system klipper crashes on startup with error: 
Internal error on command:"HYPERLAPSE"
Internal error on command:"UPDATE_DELAYED_GCODE"

log file:
[klippy-timelapse.log](https://github.com/mainsail-crew/moonraker-timelapse/files/13850553/klippy-timelapse.log)

**Comment by zellneralex** [comment]
Sorry to say, but if the plugin has issues with UPDATE_DELAYED_GCODE then I would not use it, that is a basic Klipper function

**Comment by zellneralex** [comment]
I would recommend you you get in contact with the owner of klipper_tmc_autotune

**Comment by Clon1998** [comment]
Quoting the solution to the issue caused by tmc auto tune for others here:

> It conflict with moonraker-timestamp https://github.com/mainsail-crew/moonraker-timelapse
> 
> Writing the configuration after [include timelapse.cfg] will solve this problem.


https://github.com/andrewmcgr/klipper_tmc_autotune/issues/80#issuecomment-1817318315
