### ISSUE TITLE
Add a delayed last frame

### ISSUE THREAD

**Issue by Sekenenz** [mainsail-crew/moonraker-timelapse#16]
Is it possible to modify the timelapse macro to get the last frame after the execution of the end g-code (to not have the hot-end in the last frame)? Or I missed some settings?

Btw I'm not using (and prefer to not use) the park function to avoid stringing and prolonged times.

**Comment by FrYakaTKoP** [comment]
@Sekenenz 
I never thought of such feature, but actually you should be able to use the existing macro with parameters in your endgcode to achive such.

add this to your end gcode
``` 
_SET_TIMELAPSE_SETUP PARK_ENABLE=True
TIMELAPSE_TAKE_FRAME
_SET_TIMELAPSE_SETUP PARK_ENABLE=False
```
The parkposition, speed and so on can be changed within mainsail just enable the park feature temporarily to change the setting to your liking. Then deactivate it again, if you don't like to use it while printing.

Also change the duplicatelastframe setting, to last this special frame a couple seconds

**Comment by Sekenenz** [comment]
I will asap thanks.

Ps. The printhead is already set to move in the corner in my end-gcode, so I can just add TIMELAPSE_TAKE_FRAME to it and omit the park, right?

**Comment by FrYakaTKoP** [comment]
yes, you can do that

**Comment by Sekenenz** [comment]
Just tested and unfortunately it doesn't work:

Adding only
`TIMELAPSE_TAKE_FRAME`
doesn't work.

Adding
```
_SET_TIMELAPSE_SETUP PARK_ENABLE=True
TIMELAPSE_TAKE_FRAME
_SET_TIMELAPSE_SETUP PARK_ENABLE=False
```
It works but the printer enter a loop and I have to emergency stop to block it.

The parkpos is set to back_left and duplicatelastframe to 10 (but it's always ignored)

**Comment by FrYakaTKoP** [comment]
@sekenenz
could you please provide your moonraker.log?

**Comment by Sekenenz** [comment]
https://drive.google.com/file/d/1mp-lRdDJsTrQaXr_b8ebFWIodeMRLAql/view?usp=sharing

**Comment by FrYakaTKoP** [comment]
🤔 sorry i don't see anything obvious do you have discord so we can interact directly? if so i'm "FrY Sennberg#4645" and on the klipper, mainsail, voron, ratrig and fluidd server. Just hit me up with a dm please, i'm happy to help but seems flimsy to do here.

**Comment by Sekenenz** [comment]
No but I'll register, thanks

**Comment by cmerkle** [comment]
Was this ever resolved? I'm trying to accomplish the same thing and am having the same issue

**Comment by Sekenenz** [comment]
I don't know, I gave it up at the time.
