### ISSUE TITLE
please add a uninstall script

### ISSUE THREAD

**Issue by HelgeKeck** [mainsail-crew/moonraker-timelapse#23]
hi, please add a uninstall script

thank you

**Comment by FrYakaTKoP** [comment]
i can add a uninstall script sure, but the user would still need to remove couple things manually (moonraker.conf and printer.cfg entries, slicer config) to remove everything. Don't know if a uninstaller script which just does unlink the .py and the .cfg and remove the dummy service (reverse the installer) would make much sense. What's your opinion on that? Maybe it's better to include a guide "how to uninstall", then a uninstaller script.

**Comment by HelgeKeck** [comment]
i agree, there should be a how to unisntall, exactly like the how to install, i dont see why it should be different. atm a user needs to analyze the install script if he wants to uninstall it.

**Comment by FrYakaTKoP** [comment]
i will add a guide how to uninstall

**Comment by HelgeKeck** [comment]
👍

**Comment by dvomang** [comment]
Did you ever make the uninstall guide?

**Comment by Randy1727** [comment]
Can anyone help with uninstalling timelapse.

**Comment by FrYakaTKoP** [comment]
@dvomang sorry no, still need to make a guide.

@Randy1727 
To uninstall follow

**Comment by Randy1727** [comment]
Ty for that info.

**Comment by zellneralex** [comment]
Solved with 3ac026158b2b849456bb9bf20c7663c667fa4d84

docs will follow shortly
