### ISSUE TITLE
Problems with the Park Toolhead function

### ISSUE THREAD

**Issue by Bmerino16** [mainsail-crew/moonraker-timelapse#34]
Hello, I just installed the timelapse function and it is working. But I have problems with the Park Toolhead option, although I have it activated it does not work. What can I do in this case?

**Comment by FrYakaTKoP** [comment]
@Bmerino16 hard to guess without more information. Can you provide a moonraker.log and klippy.log? Also which os your on? Do you may have old config from the first version of the plugin in your printer.cfg?

**Comment by Bmerino16** [comment]
@FrYakaTKoP Hi, sorry or the late. here you have the the moonraker.log and klippy.log

[klippy.log](https://github.com/mainsail-crew/moonraker-timelapse/files/7893245/klippy.log)

[moonraker.log](https://github.com/mainsail-crew/moonraker-timelapse/files/7893246/moonraker.log)


For the OS version, I don't know i you mean this:
![image](https://user-images.githubusercontent.com/51961711/150042235-5e674db3-7d20-4611-ae37-2311d5b32628.png)

This is the only thing I have in printer.cfg

![image](https://user-images.githubusercontent.com/51961711/150042562-8e4e061d-2af7-467b-9310-586b30715541.png)

![image](https://user-images.githubusercontent.com/51961711/150042746-69cb0f21-2aa4-4cb0-9e55-a1c5b5e7da96.png)


And in the moonraker.conf the update manager and the [timelapse] section.

I appreciate your help!

**Comment by zellneralex** [comment]
Can you do me a favor an€ run GET_TIMELAPSE_SETUP in the console and post the result

**Comment by zellneralex** [comment]
And I hope you do not have that gcode macro in your printer.cfg as that would override our macro and would explain all. Your config does not show that btw

**Comment by FrYakaTKoP** [comment]
@Bmerino16 remove the "TIMELAPSE_TAKE_FRAME" Macro from the printer.cfg this is the old version without the parkfeature and because it's defined after the include of timelapse.cfg it overwrites the new one in there.

**Comment by Bmerino16** [comment]
@FrYakaTKoP I just followed your recommendation and removed the "TIMELAPSE TAKE FRAME" macro. Now it works perfectly.

I really appreciate your help!

**Comment by FrYakaTKoP** [comment]
your welcome! 
closing the issue because it's resolved
