### ISSUE TITLE
CUSTOM_POS_X ERROR

### ISSUE THREAD

**Issue by gurusonwheels** [mainsail-crew/moonraker-timelapse#35]
keep getting this error in my gcode console :

Error evaluating 'gcode_macro _SET_TIMELAPSE_SETUP:gcode': CommandError: CUSTOM_POS_X=0.0 must be within [6.0 - 350.0]

i have these versions 
klipper
v0.10.0-225-g6e6ad7b5
moonraker
v0.7.1-285-g505c1bf
timelapse
v0.0.1-96-g90a277c
z_calibration
v0.8.0-7-gcb68379
mainsail
v2.1.0-rc1

**Comment by zellneralex** [comment]
Ok that is easy to fix you have a special x in setting your minimum is at 6

**Comment by zellneralex** [comment]
I guess the best is to add it to a kind of FAQ

**Comment by zellneralex** [comment]
We decided to change the default to 10  as we get the 2nd USER with the same issue.

See c86105449c8babf0df5d13d533b66f6d3ea19896
