### ISSUE TITLE
AttributeError: 'Timelapse' object has no attribute 'webcams_db'

### ISSUE THREAD

**Issue by BillyNate** [mainsail-crew/moonraker-timelapse#38]
I'm getting this error when running the `TIMELAPSE_TAKE_FRAME` GCode macro:  
`AttributeError: 'Timelapse' object has no attribute 'webcams_db'`.

I'm using Fluidd. There's no `[webcam]` section in my moonraker.conf but the webcam is showing just fine on the dashboard.  
In [configuration.md](https://github.com/mainsail-crew/moonraker-timelapse/blob/main/docs/configuration.md#camera) it says _"Alternatively you can configure 'snapshoturl', 'flip_x' and 'flip_y' in the moonraker.conf if your frontend doesn't support the webcams namespace of moonraker DB."_ But setting the `snapshoturl` doesn't seem to fix the error.

**Comment by FrYakaTKoP** [comment]
sorry didn't want to close it, was happen because of the mention in the commit message, anyway the commit [2b877ef](https://github.com/mainsail-crew/moonraker-timelapse/commit/2b877ef6fbf2e13d03efd09eab6a857905c62b0a) should resolve this issue. Feel free to reopen it if your problem persists
