### ISSUE TITLE
unable to set [timelapse] in moonraker.cfg file

### ISSUE THREAD

**Issue by pappicio** [mainsail-crew/moonraker-timelapse#4]
if I insert only: 
[timelapse]

all works, but if I insert into:
[timelapse]
enabled: False

error:
% fluidd avvisi trovati.
Moonraker ha problemi con dei plugin. Controlla i tuoi log, aggiorna la tua configurazione e riavvia moonraker.
timelapse
Puoi trovare la configurazione dei plug-in Moonraker qui .

**Comment by sofger** [comment]
Hi!
I found the bug, fixed it, and opened a pull request:
https://github.com/mainsail-crew/moonraker-timelapse/pull/7/commits/1ac0122560596226e2d93fe57d80365616790da8

**Comment by pappicio** [comment]
Tested, works well!! Thanks

**Comment by FrYakaTKoP** [comment]
sorry i introduced this bug while fixing linting and didn't test it afterwards, sorry to everyone had this issue
