### ISSUE TITLE
Timelapse On/Off switch (Request-Enhancement)

### ISSUE THREAD

**Issue by acosano** [mainsail-crew/moonraker-timelapse#45]
Is there anyway to have a button to switch on/off timelapse. You don't need always to have a timelapse.

**Comment by FrYakaTKoP** [comment]
@acosano 
There is a on/off switch in Mainsail already:
![grafik](https://user-images.githubusercontent.com/10913183/157858687-1aec22f5-6fa8-497b-b399-f6a408b47a35.png)

If you use Fluidd you need to open a feature request there to get this button
