### ISSUE TITLE
Remove old Timelapses

### ISSUE THREAD

**Issue by 10htts** [mainsail-crew/moonraker-timelapse#51]
Hello! (New to GitHub, wasn't sure where to put this...)
Just wondering if it would be hard to add an option to delete old Time lapses? (Possible filters: X days, X  videos, X GB of data)

Thanks :)

**Comment by FrYakaTKoP** [comment]
sorry for the  late answer. 

I don't like the idea of the plugin deleting stuff, but if you like to have such feature you can always setup a "cron job" to do such for you.
