### ISSUE TITLE
after clicking first tiime render during print all later renders are the same length without the extra layers.

### ISSUE THREAD

**Issue by harellevy** [mainsail-crew/moonraker-timelapse#54]
after clicking render during print it saves to that exact layer as mp4, all the other times during print it exports the same file with different filename and without the new layers that have been captured. Still don't know what would happen at the end of the print. I'll update.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/2623446/168496768-6d34fa1f-a642-428a-81a8-b7d0d246e33a.png">
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/2623446/168496777-8b00d41e-4d1d-4d65-87dc-faaf1c77bc75.png">

**Comment by harellevy** [comment]
running on fluidd UI

**Comment by FrYakaTKoP** [comment]
rendering isn't intended but should work fine. Are you sure there are still new frames captured?

**Comment by harellevy** [comment]
@FrYakaTKoP Thanks for the quick reply, yes, you can see behind the rendered modal in the screenshot the last frames. I just saw it missed frames 40-44 so it skipped the rest. but after 44 it continued to capture. It's really weird.

**Comment by harellevy** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/2623446/168497323-c98ab9b2-fdcc-48bf-90e3-d132775765ac.png">

**Comment by harellevy** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/2623446/168497330-4f9ee17b-dcad-4e99-b2d0-14df96788717.png">

**Comment by harellevy** [comment]
it keeps printing. but layers 40-44 wasn't captured.
Now this was the last captured frame currently printing
<img width="499" alt="image" src="https://user-images.githubusercontent.com/2623446/168497363-58c92ecb-c5f7-4846-ad62-215bbb7cc7ce.png">

**Comment by harellevy** [comment]
This is what i get in the uncaptured frames:
```
{"error": {"code": 404, "message": "Not Found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/pi/moonraker-env/lib/python3.7/site-packages/tornado/web.py\", line 1704, in _execute\n    result = await result\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 690, in get\n    self.root, absolute_path)\n\n  File \"/home/pi/moonraker-env/lib/python3.7/site-packages/tornado/web.py\", line 2778, in validate_absolute_path\n    raise HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not Found\n"}}
```

**Comment by FrYakaTKoP** [comment]
strange that there is a 404 in some frames. The url which get captured shouldn't change randomly, therefore a "not found" shouldn't be possible after a sucessfull capture.

can you upload the full moonraker.log of this print?
