### ISSUE TITLE
// Timelapse: disabled, take frame ignored (Help)

### ISSUE THREAD

**Issue by leelydlml** [mainsail-crew/moonraker-timelapse#59]
Hey for some odd reason my console says 
// Timelapse: disabled, take frame ignored
and I went to the timelapse.conf file and changed
[gcode_macro TIMELAPSE_TAKE_FRAME]
description: Take Timelapse shoot
variable_enable: True
variable_takingframe: True
to saying true and once I save and restart it just resets it to say false. 
I believe this is the issue for it ignoring the take frame command but I am new to coding and moonraker.
[Config Files.zip](https://github.com/mainsail-crew/moonraker-timelapse/files/8981655/Config.Files.zip)

**Comment by fbeauKmi** [comment]
Your problem seems to be the moonraker.conf . Replace all the `=` by `:` in timelapse section

**Comment by JackBailey** [comment]
If anyone has this error and their conf already uses `:`, try just resetting your settings for the timelapse and configuring it again. Doesn't look like it changed anything but the timelapse works again 🤷

**Comment by zemlyanskii-artem** [comment]
В настройках тайлапса нужно выключить Использовать откат из прошивки и все работает !
я вот только установил сделал однин тайлапс и все отказался печатать ! долго я икал причину и раз 10 все по кругу случайно выяснил причину!
![2025-01-08_16-19-19](https://github.com/user-attachments/assets/31a78059-797f-409a-b3e1-e06d12d38ef7)
надеюсь другим людям поможет !)
