### ISSUE TITLE
Minor bug in Macro GET_TIMELAPSE_SETUP do not return Retraction settings

### ISSUE THREAD

**Issue by fbeauKmi** [mainsail-crew/moonraker-timelapse#61]
Macro only returns retract settings  if fw_retract = True, Change test 
change line 26 of timelapse.cfg by 
```
{% if not tl.extruder.fw_retract %}
```

**Comment by zellneralex** [comment]
Hi, that is correct. The idea behind that is simple if you have set fw_retract to false these values have no function for you and therefor they are not shown.

**Comment by zellneralex** [comment]
Forgot my last statement, you are correct! I will correct it over the weekend.
