### ISSUE TITLE
Watermark Feature Request

### ISSUE THREAD

**Issue by GTBannon** [mainsail-crew/moonraker-timelapse#62]
I currently export all renders to video editor, add in watermark, then post to social media. It would be nice if there was an overlay where an already modified photo (transparency / clear background) could be uploaded as an overlay of the render process. I would even be okay with placing it blind, based off the resolution of my webcam. Thanks!

**Comment by FrYakaTKoP** [comment]
thanks for the request but it's a duplicate of #17, i will close this and update on the other one.
