### ISSUE TITLE
Add support for moving only X or Y before taking picture

### ISSUE THREAD

**Issue by steckdev** [mainsail-crew/moonraker-timelapse#74]
My camera is position such that I only need the Y axis to be in the correct position before taking the screenshot. This will prevent additional movement on X that is not needed. 

I can adjust the "seam position" so that the X is in a consistent location on layer change. Although it may move the head around a little bit on the X axis. The print part would be the correct location.

This would increase the speed of the print and minimize jerking of the spool which I is causing my "co-extrusion" printed parts to be more inconsistent with photos.

**Comment by zellneralex** [comment]
Need to be discussed in the team but in general possible.
I would add it to the park position option.

**Comment by zellneralex** [comment]
See https://github.com/mainsail-crew/moonraker-timelapse/tree/park_modes. Will be merged soon

**Comment by zellneralex** [comment]
Added the 2 park modes. Mainsail will allow to set them in V2.5
