### ISSUE TITLE
still having some config issues

### ISSUE THREAD

**Issue by jbrandek** [mainsail-crew/moonraker-timelapse#8]
some fixed but still having this ones:

check the logfile and fix the issue.

Following plugin has an error:

timelapse
Invalid config option 'output_framerate: 20 # Note: this will be ignored if variable_fps is enabled' detected in section [timelapse]. To solve this issue check your moonraker config. This option is invalid and has to be deleted or fixed. In the future this will result in a startup error.

Invalid config option 'time_format_code: %Y%m%d_%H%M' detected in section [timelapse]. To solve this issue check your moonraker config. This option is invalid and has to be deleted or fixed. In the future this will result in a startup error.

Invalid config option 'snapshoturl: http://localhost:8080/?action=snapshot' detected in section [timelapse]. To solve this issue check your moonraker config. This option is invalid and has to be deleted or fixed. In the future this will result in a startup error.

Invalid config option 'pixelformat: yuv420p' detected in section [timelapse]. To solve this issue check your moonraker config. This option is invalid and has to be deleted or fixed. In the future this will result in a startup error.

Invalid config option 'previewimage: True' detected in section [timelapse]. To solve this issue check your moonraker config. This option is invalid and has to be deleted or fixed. In the future this will result in a startup error.

**Comment by jbrandek** [comment]
Sorry my bad learned the hard way you cannot comment in same line as a value is set

now the only thing is not working is previewImage

Invalid config option 'previewimage: True' detected in section [timelapse]. To solve this issue check your moonraker config. This option is invalid and has to be deleted or fixed. In the future this will result in a startup error.

**Comment by FrYakaTKoP** [comment]
@jbrandek could you please provide a moonraker.log?

**Comment by FrYakaTKoP** [comment]
it seems like moonraker config helper doesn't like the uppercase "I" in the config name. 

i pushed fa81ef3 to fix it.

thanks for finding and reporting it, since i use a alpha version of mainsail which includes those settings in the Ui i would never catch those!

**Comment by jbrandek** [comment]
Thanks for making the plugin and fix and reply so fast

**Comment by FrYakaTKoP** [comment]
your welcome again thanks for testing and feedback
