### ISSUE TITLE
Custom Install paths create installer issues

### ISSUE THREAD

**Issue by Supruh** [mainsail-crew/moonraker-timelapse#87]
Custom install paths make issues with the installer, which assumes to find `klipper_config` under `/home/users`, however for some reason my klipper install is simply under `~klipper`. I have tried to link the folders as shown in a previous issue however now I am running into issues in mainsail where `/home/user/printer_data/config/timelapse.cfg` does not exist. As a new user to linux, I feel given enough time I can figure something out myself, however custom install paths would be a much appreciated addition

**Comment by Supruh** [comment]
I was able to fix it however I still feel custom install paths may benefit future users who may need it

**Comment by zellneralex** [comment]
We need to adopt the new moonraker paths (printer_data/…). The installer is still tailored for the old standard.

**Comment by FrYakaTKoP** [comment]
i have plans to rework the old installer to work with the old and the new path system. Also a custom path parameter should be possible.

**Comment by Supruh** [comment]
Cool! I ended up fixing it, but thanks for getting to it
