### ISSUE TITLE
Print is pausing when after I hit start due to unknown command.

### ISSUE THREAD

**Issue by dvomang** [mainsail-crew/moonraker-timelapse#90]
![image](https://user-images.githubusercontent.com/3137075/211468185-e8a4fc09-31bd-4b28-b424-cc6891548eb9.png)
I am getting this error when starting a print.

**Comment by zellneralex** [comment]
That means you did not include the timelapse.cfg to your printer.cfg.

so add

[include timelapse.cfg] inside your printer.cfg

**Comment by zellneralex** [comment]
See also https://github.com/mainsail-crew/moonraker-timelapse/blob/main/docs/configuration.md#define-the-gcode-macro

**Comment by zellneralex** [comment]
No response from user so I assume it is fixed.

**Comment by Diegolgo** [comment]
is a know bug. just restart klipper. (or mcu).
it's happen once in a time (too many time betwen this error, always forgot, and, like  you, start to search about this, find "solutiones" but the problem  just that. restart.
