### ISSUE TITLE
Park toolhead never resume

### ISSUE THREAD

**Issue by masgar** [mainsail-crew/moonraker-timelapse#93]
I enabled park toolhead. It works fine. When the TIMELAPSE_TAKE_FRAME is executed print is paused, toolhead moves at parking position and picture is taken but the print never resumes and I have to resume it manually.

What I'm doing wrong?

**Comment by FrYakaTKoP** [comment]
could you reproduce the issue and send me the klippy.log and moonraker.log files so i can investigate?
